import { useEffect,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search,SlidersHorizontal } from 'lucide-react';
import { useProducts } from '../hooks/useProducts';
import ProductCard from '../components/ProductCard';
import SkeletonCard from '../components/SkeletonCard';
import { CATEGORIES,CATEGORY_LABELS } from '../lib/constants';
import { setSEO } from '../lib/seo';
export default function Products(){const [p]=useSearchParams(),[category,setCategory]=useState(p.get('category')||'all'),[search,setSearch]=useState(''),[min,setMin]=useState(0),[max,setMax]=useState(500000),[sort,setSort]=useState('newest'),[mobile,setMobile]=useState(false);const {products,loading}=useProducts({category,search,minPrice:min,maxPrice:max,sort});useEffect(()=>setSEO('Shop | The Store 99','Browse clothing, shoes and accessories from The Store 99.'),[]);return <section className="section-pad"><div className="container-x"><div className="flex items-end justify-between mb-8"><div><p className="text-gold uppercase tracking-[.25em] text-xs font-black">The collection</p><h1 className="display text-6xl mt-2">SHOP 99</h1></div><button className="md:hidden border rounded-full px-4 py-3 flex gap-2" onClick={()=>setMobile(!mobile)}><SlidersHorizontal size={17}/>Filters</button></div><div className="grid lg:grid-cols-[230px_1fr] gap-10"><aside className={(mobile?'block ':'hidden ')+'lg:block'}><div className="lg:sticky lg:top-28 space-y-7"><div><h3 className="font-black mb-3">Category</h3>{['all',...CATEGORIES].map(c=><label key={c} className="flex gap-2 items-center text-sm py-1"><input type="checkbox" checked={category===c} onChange={()=>setCategory(c)} className="accent-[#D4AF37]"/>{c==='all'?'All':CATEGORY_LABELS[c]}</label>)}</div><div><h3 className="font-black mb-3">Price</h3><div className="flex gap-2"><input type="number" value={min} onChange={e=>setMin(Number(e.target.value))} className="w-full border rounded-lg px-2 py-2 bg-transparent"/><input type="number" value={max} onChange={e=>setMax(Number(e.target.value))} className="w-full border rounded-lg px-2 py-2 bg-transparent"/></div><input type="range" min="0" max="500000" step="5000" value={max} onChange={e=>setMax(Number(e.target.value))} className="w-full accent-[#D4AF37] mt-3"/></div><select value={sort} onChange={e=>setSort(e.target.value)} className="w-full border rounded-xl px-3 py-3 bg-transparent"><option value="newest">Newest</option><option value="low">Price Low-High</option><option value="high">Price High-Low</option></select></div></aside><div><div className="flex items-center gap-3 border rounded-full px-4 py-2 mb-7"><Search size={18} className="text-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..." className="flex-1 bg-transparent outline-none py-2"/></div>{loading?<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{Array.from({length:6}).map((_,i)=><SkeletonCard key={i}/>)}</div>:products.length?<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{products.map(p=><ProductCard product={p} key={p.id}/>)}</div>:<div className="py-24 text-center text-muted">No products match those filters.</div>}</div></div></div></section>}
