import { useEffect,useMemo,useState } from 'react';
import { useParams,Link } from 'react-router-dom';
import { Minus,Plus,ShoppingBag } from 'lucide-react';
import toast from 'react-hot-toast';
import { useProduct } from '../hooks/useProducts';
import { useCart } from '../context/CartContext';
import { money } from '../lib/format';
import ImageGallery from '../components/ImageGallery';
import SizeSelector from '../components/SizeSelector';
import Spinner from '../components/Spinner';
import { setSEO } from '../lib/seo';
export default function ProductDetail(){const {id}=useParams(),{product,loading}=useProduct(id),{addToCart}=useCart(),[size,setSize]=useState(''),[qty,setQty]=useState(1);useEffect(()=>{if(product)setSEO(product.name+' | The Store 99',product.description||'Shop '+product.name)},[product]);const selected=useMemo(()=>product?.product_sizes?.find(s=>s.size===size),[product,size]);if(loading)return <div className="min-h-[60vh] grid place-items-center"><Spinner/></div>;if(!product)return <div className="section-pad text-center">Product not found.</div>;const sizes=product.product_sizes||[],available=selected?.stock_qty||product.stock||0;return <section className="section-pad"><div className="container-x"><Link to="/products" className="text-sm text-muted">← Back to collection</Link><div className="grid lg:grid-cols-2 gap-10 mt-6"><ImageGallery images={product.product_images||[]}/><div className="lg:py-8"><span className="uppercase tracking-widest text-xs font-black text-gold">{product.category}</span><h1 className="display text-5xl sm:text-7xl mt-3">{product.name}</h1><p className="text-2xl font-black text-gold mt-5">{money(product.price)}</p><div className="mt-8"><h3 className="font-black mb-3">Select size</h3><SizeSelector sizes={sizes} selected={size} onChange={s=>{setSize(s);setQty(1)}}/>{sizes.length>0&&!size&&<p className="text-sm text-red-500 mt-2">Choose a size to continue.</p>}</div><p className="text-sm text-muted mt-4">{available>0?available+' items left':'Out of stock'}</p><div className="flex items-center gap-3 mt-6"><div className="flex items-center border rounded-full"><button className="p-3" disabled={qty<=1} onClick={()=>setQty(q=>q-1)}><Minus size={16}/></button><span className="w-8 text-center">{qty}</span><button className="p-3" disabled={qty>=available} onClick={()=>setQty(q=>Math.min(available,q+1))}><Plus size={16}/></button></div><button disabled={!available||(!size&&sizes.length>0)} onClick={()=>{addToCart(product,size||'One Size',qty);toast.success('Added to cart')}} className="flex-1 py-4 rounded-full bg-gold text-black font-black disabled:opacity-40"><ShoppingBag size={18} className="inline mr-2"/>Add to Cart</button></div><div className="mt-10 pt-8 border-t"><h3 className="font-black mb-3">Description</h3><p className="text-muted leading-8">{product.description||'A signature Store 99 piece.'}</p></div></div></div></div></section>}
